var searchData=
[
  ['sarsalearninginput',['SarsaLearningInput',['../d4/d53/structcengine_1_1rl_1_1SarsaLearningInput.html',1,'cengine::rl']]],
  ['sarsalearningoutput',['SarsaLearningOutput',['../d4/dd7/structcengine_1_1rl_1_1SarsaLearningOutput.html',1,'cengine::rl']]],
  ['sarsatablelearning',['SarsaTableLearning',['../de/df2/classcengine_1_1rl_1_1SarsaTableLearning.html',1,'cengine::rl']]],
  ['scalardirichletbcfunc',['ScalarDirichletBCFunc',['../d0/dee/classkernel_1_1numerics_1_1ScalarDirichletBCFunc.html',1,'kernel::numerics']]],
  ['scalarfvsystem',['ScalarFVSystem',['../d2/dd2/classkernel_1_1numerics_1_1ScalarFVSystem.html',1,'kernel::numerics']]],
  ['scalarfvsystem_3c_20dim_2c_20assemblepolicy_2c_20solutionpolicy_20_3e',['ScalarFVSystem&lt; dim, AssemblePolicy, SolutionPolicy &gt;',['../d2/dd2/classkernel_1_1numerics_1_1ScalarFVSystem.html',1,'kernel::numerics']]],
  ['scalarfvsystem_3c_20dim_2c_20pressureassemblypolicy_2c_20solutionpolicy_20_3e',['ScalarFVSystem&lt; dim, PressureAssemblyPolicy, SolutionPolicy &gt;',['../d2/dd2/classkernel_1_1numerics_1_1ScalarFVSystem.html',1,'kernel::numerics']]],
  ['scalarfvsystem_3c_20dim_2c_20velocitassemblypolicy_2c_20solutionpolicy_20_3e',['ScalarFVSystem&lt; dim, VelocitAssemblyPolicy, SolutionPolicy &gt;',['../d2/dd2/classkernel_1_1numerics_1_1ScalarFVSystem.html',1,'kernel::numerics']]],
  ['scalarvar',['ScalarVar',['../d7/dc2/classkernel_1_1numerics_1_1ScalarVar.html',1,'kernel::numerics']]],
  ['scaleddif',['ScaledDif',['../db/d5b/structkernel_1_1ScaledDif.html',1,'kernel']]],
  ['scaledsum',['ScaledSum',['../db/d39/structkernel_1_1ScaledSum.html',1,'kernel']]],
  ['searchable_5fpriority_5fqueue',['searchable_priority_queue',['../d8/d8b/classkernel_1_1searchable__priority__queue.html',1,'kernel']]],
  ['sigmoidfunction',['SigmoidFunction',['../dd/d54/classkernel_1_1SigmoidFunction.html',1,'kernel']]],
  ['sigmoidfunction_3c_20hypothesisfn_20_3e',['SigmoidFunction&lt; HypothesisFn &gt;',['../dd/d54/classkernel_1_1SigmoidFunction.html',1,'kernel']]],
  ['simpletaskbase',['SimpleTaskBase',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simpletaskbase_3c_20actor_3a_3areturn_5ft_20_3e',['SimpleTaskBase&lt; Actor::return_t &gt;',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simpletaskbase_3c_20dynvec_3c_20real_5ft_20_3e_20_3e',['SimpleTaskBase&lt; DynVec&lt; real_t &gt; &gt;',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simpletaskbase_3c_20null_20_3e',['SimpleTaskBase&lt; Null &gt;',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simpletaskbase_3c_20real_5ft_20_3e',['SimpleTaskBase&lt; real_t &gt;',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simpletaskbase_3c_20reductionoptp_3a_3avalue_5ftype_20_3e',['SimpleTaskBase&lt; ReductionOpTp::value_type &gt;',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simpletaskbase_3c_20resulttp_20_3e',['SimpleTaskBase&lt; ResultTp &gt;',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simpletaskbase_3c_20typename_20actor_3a_3areturn_5ft_20_3e',['SimpleTaskBase&lt; typename Actor::return_t &gt;',['../db/d61/classkernel_1_1SimpleTaskBase.html',1,'kernel']]],
  ['simulator',['Simulator',['../de/d85/classcengine_1_1rl_1_1Simulator.html',1,'cengine::rl']]],
  ['smo',['Smo',['../df/dec/classparml_1_1Smo.html',1,'parml']]],
  ['smo_3c_20cput_5fc11_20_3e',['Smo&lt; cput_c11 &gt;',['../d1/d63/classparml_1_1Smo_3_01cput__c11_01_4.html',1,'parml']]],
  ['smo_3c_20serial_20_3e',['Smo&lt; serial &gt;',['../d2/dc4/classparml_1_1Smo_3_01serial_01_4.html',1,'parml']]],
  ['smobase',['SmoBase',['../d8/dbb/classparml_1_1SmoBase.html',1,'parml']]],
  ['smocontrol',['SmoControl',['../dd/d5d/structparml_1_1SmoControl.html',1,'parml']]],
  ['smoinfo',['SmoInfo',['../dc/dfe/structparml_1_1SmoInfo.html',1,'parml']]],
  ['squaredlossfunc',['SquaredLossFunc',['../dc/d90/classparml_1_1SquaredLossFunc.html',1,'parml']]],
  ['squaredlossfunc_3c_20armavecdataset_3c_20t_20_3e_20_3e',['SquaredLossFunc&lt; ArmaVecDataSet&lt; T &gt; &gt;',['../d2/d82/classparml_1_1SquaredLossFunc_3_01ArmaVecDataSet_3_01T_01_4_01_4.html',1,'parml']]],
  ['ssefunction',['SSEFunction',['../db/d93/classkernel_1_1SSEFunction.html',1,'kernel']]],
  ['ssefunction_3c_20hypothesisfn_2c_20partitionedtype_3c_20datasettype_20_3e_2c_20partitionedtype_3c_20labelstype_20_3e_2c_20regularizerfn_20_3e',['SSEFunction&lt; HypothesisFn, PartitionedType&lt; DataSetType &gt;, PartitionedType&lt; LabelsType &gt;, RegularizerFn &gt;',['../d5/d80/classkernel_1_1SSEFunction_3_01HypothesisFn_00_01PartitionedType_3_01DataSetType_01_4_00_01Parti43a22fb663590fbf435119fc2a382de9.html',1,'kernel']]],
  ['steadystatenssystem',['SteadyStateNSSystem',['../dc/d8b/classkernel_1_1numerics_1_1SteadyStateNSSystem.html',1,'kernel::numerics']]],
  ['stoppabletask',['StoppableTask',['../dc/d8d/classkernel_1_1StoppableTask.html',1,'kernel']]],
  ['sum',['Sum',['../de/d38/classkernel_1_1Sum.html',1,'kernel']]],
  ['sum_3c_20resulttp_20_3e',['Sum&lt; ResultTp &gt;',['../de/d38/classkernel_1_1Sum.html',1,'kernel']]],
  ['sumop',['SumOp',['../dd/d42/structparml_1_1par__batch__gd__detail_1_1SumOp.html',1,'parml::par_batch_gd_detail']]],
  ['svm',['Svm',['../d2/d8c/classparml_1_1Svm.html',1,'parml']]],
  ['syncvaluefuncitr',['SyncValueFuncItr',['../d3/dfe/classcengine_1_1rl_1_1SyncValueFuncItr.html',1,'cengine::rl']]],
  ['syncvaluefuncitrinput',['SyncValueFuncItrInput',['../df/d45/structcengine_1_1rl_1_1SyncValueFuncItrInput.html',1,'cengine::rl']]],
  ['syncvaluefuncitroutput',['SyncValueFuncItrOutput',['../d6/d7e/structcengine_1_1rl_1_1SyncValueFuncItrOutput.html',1,'cengine::rl']]],
  ['sysstate',['SysState',['../df/da3/classkernel_1_1dynamics_1_1SysState.html',1,'kernel::dynamics']]],
  ['sysstate_3c_203_20_3e',['SysState&lt; 3 &gt;',['../df/da3/classkernel_1_1dynamics_1_1SysState.html',1,'kernel::dynamics']]]
];
